<script>
    import { generateSiaxAst } from "$lib/siax/language/parse/ast";
    import {
        Card,
        CardContent,
        CardDescription,
        CardHeader,
        CardTitle,
    } from "./ui/card";
    import CodeMirrorEditor from "./CodeMirrorEditor.svelte";
    import { SiaxBytecodeGenerator } from "$lib/siax/language/bytecode/generate";
    import {
        Accordion,
        AccordionContent,
        AccordionItem,
        AccordionTrigger,
    } from "./ui/accordion";

    let { code = $bindable() } = $props();

    const byteCodeGen = new SiaxBytecodeGenerator(1024);

    let generatedCodeFromAst = $derived.by(() => {
        let ast = generateSiaxAst(code);
        if (!ast) return null;
        return byteCodeGen.generate(ast);
    });
</script>

<Card class="max-w-3xl w-full h-full">
    <CardHeader>
        <CardTitle class="tracking-tighter text-xl font-bold"
            >Bytecode</CardTitle
        >
        <CardDescription>
            Using code defined in the <b>language</b> tab, you can visualize the program
            output here.
        </CardDescription>
    </CardHeader>

    <CardContent class="flex flex-col w-full gap-2">
        <span class="font-bold tracking-tight text-lg"
            >Inputted code (From Language tab)</span
        >
        <code class="bg-background outline p-2 rounded-md mb-6">
            {code.length > 0 ? code : "No Code"}
        </code>
        <span class="font-bold tracking-tight text-lg">Generated Code:</span>
        <code class="bg-background outline p-2 rounded-md">
            {generatedCodeFromAst && code.length > 0
                ? generatedCodeFromAst.tag === "ok"
                    ? generatedCodeFromAst.value.join(" ")
                    : `Error: ${generatedCodeFromAst.value}`
                : "Invalid bytecode generation"}
        </code>
        <Accordion type="single">
            <AccordionItem value="stats">
                <AccordionTrigger>Stats</AccordionTrigger>
                <AccordionContent>
                    <ul class="list-disc pl-6">
                        <li>Code length: {code.length} characters</li>
                        <li>
                            Generated bytecode length:{" "}
                            {generatedCodeFromAst &&
                            generatedCodeFromAst.tag === "ok"
                                ? generatedCodeFromAst.value.length
                                : "N/A"}{" "}
                            bytes
                        </li>
                    </ul>
                </AccordionContent>
            </AccordionItem>
        </Accordion>
    </CardContent>
</Card>
